### ISSUE TITLE
Implement some execve mechanism 

### ISSUE THREAD

**Issue by milot-mirdita** [biowasm/biowasm#39]
I am still trying to get MMseqs2 fo fully work in web assembly. For this I would need `execve` to work. In MMseqs2 we use bash basically as a scripting language/workflow engine.

Essentially we have:
```
MMseqs2 workflow (c++)
  --> execve
      --> bash (or dash, busybox ash, any posix sh)
          --> execve
              --> mmseqs call1 (c++)
              --> mmseqs call2 
              --> ...
```

I've also managed to compile https://github.com/mgree/libdash for biowasm and I implemented something to call into javascript/aioli from C++ if an execve system call is encountered in https://github.com/milot-mirdita/biowasm/commit/0959917760ccc100831c901c2edb03c3010b4815.

Now I would need to implement an `execve` function in aioli.worker.js to spawn a new wasm module, sync the file system, wait until everything finishes, and sync the file system again. 

I could start hacking something, but I don't really have a bigger picture of how this feature should look like. If this should be integrated with aioli/biowasm somehow then it would need also some kind of `PATH` resolution through the biowasm index I guess? Do you have any ideas/opinions?

Alternatively, I could think of implementing this 100% inside MMseqs2 somehow, without additional biowasm/aioli support.

**Comment by robertaboukhalil** [comment]
Hey @milot-mirdita! Sorry, just going through the backlog of issues :)

> I would need to implement an execve function in aioli.worker.js to spawn a new wasm module, sync the file system, wait until everything finishes, and sync the file system again.

Hmm, that sounds difficult! 😅  I wonder if you could instead use 1 Aioli Worker that you call repeatedly from your JavaScript code; that way you also only have 1 file system to work with, and no changes needed to biowasm/aioli.

One way to do that would be to modify your `main()` function so that it exposes the functions `mmseqs call1` and `mmseqs call2` via flags, then you can do something like this in your JS code:

```js
mmseqs2 = new Aioli("mmseqs2/1.2.3");
await mmseqs2.init();
await mmseqs2.exec("--call1")
await mmseqs2.exec("--call2")
```
