### ISSUE TITLE
plans to publish to npm?

### ISSUE THREAD

**Issue by luizirber** [biowasm/biowasm#6]
Hi!

any plans to publish the generated wasm packages to npm? Maybe in a [`@biowasm`](https://docs.npmjs.com/about-scopes) scope?

**Comment by robertaboukhalil** [comment]
That's a great idea! I'll look into that

**Comment by robertaboukhalil** [comment]
Hey Luiz,

Since I wanted to be able to use the wasm packages from a hosted site as well without managing two sources, I ended up making a small CDN for those wasm packages: [cdn.sandbox.bio](https://cdn.sandbox.bio) (it's hosted on Cloudflare to ensure speed and reliability) 😀 

That means it's really easy to get started with an app, see [here](https://github.com/biowasm/aioli#getting-started) for an app that runs `samtools` on a file provided by the user.

I've also created a biowasm scope in npm to host Aioli (the JS library for launching/managing biowasm modules in a webworker): https://www.npmjs.com/package/@biowasm/aioli

**Comment by luizirber** [comment]
That's awesome, thanks!
