### ISSUE TITLE
kalign is failed to align more than ~3000 sequences

### ISSUE THREAD

**Issue by nikolay-alemasov** [biowasm/biowasm#61]
I have two samples of fasta-files of which the [former](https://github.com/biowasm/biowasm/files/8000773/random_3000.fa.zip) is processed successfully but the [latter](https://github.com/biowasm/biowasm/files/8000774/random_4000.fa.zip) is failed with the familiar exception (have already seen in #60):
```
RangeError: Maximum call stack size exceeded
    at kalign.wasm:0x277e
    at kalign.wasm:0xbc82
    at kalign.wasm:0xd417
    at kalign.wasm:0x6fce
    at kalign.wasm:0x7342
    at kalign.wasm:0x7353
    at kalign.wasm:0x7353
    at kalign.wasm:0x7353
    at kalign.wasm:0x7353
    at kalign.wasm:0x7353
```
The only difference of these files is number of sequences: 3000 and 4000.
Is the issue is linked with emscripten FS implementation? Or maybe JS-module initialization? Or what else? 

It could probably stem from `emcc` compilation unequal to the original `gcc`? Since the initial linux-compiled `kalign` can readily process both of these files. Would it be possible at all that we faced some not-enough-memory or too-little-stack issue?

**Comment by robertaboukhalil** [comment]
Looks like there's too much recursion in kalign for the stack to handle it. The recursion happens when `bisecting_kmeans_serial()` calls itself [here](https://github.com/TimoLassmann/kalign/blob/4c3ca01a75e78852a7916a08826e1e5126602ed1/src/bisectingKmeans.c#L124).

What's really interesting is that I see different things based on the browser:
* On Chrome: 3000 sequences actually fails for me, I can only do 2500 sequences
* On Firefox: 4000 sequences works just fine, and even 8000 works!

Based on the discussion at https://github.com/emscripten-core/emscripten/issues/13043, sounds like this might be a bug in the V8 engine.

**Comment by nikolay-alemasov** [comment]
It looks like we should try [one](https://github.com/pyodide/pyodide/issues/821#issuecomment-738871064) of suggestions there on `TOTAL_STACK` should mild the problem.

**Comment by nikolay-alemasov** [comment]
> Unfortunately, changing `TOTAL_STACK` won't help since it's an issue with the WebAssembly runtime

In fact for us it would not be practical solution since it suggests rebuilding the compiler at first that is out of the usual pipeline for adding a tool. Anyway I am going to track the issue. Thank you for your assistance, @robertaboukhalil !

**Comment by robertaboukhalil** [comment]
No problem!
