### ISSUE TITLE
Adding agc to biowasm

### ISSUE THREAD

**Issue by niemasd** [biowasm/biowasm#92]
Hey, Robert! I was hoping to add the [Assembled Genomes Compressor](https://github.com/refresh-bio/agc) (`agc`) to biowasm, as it's really good at compressing collections of viral (as well as other) genomes. I was able to add the `agc` repo as `src` in my fork of the `biowasm` repo:

https://github.com/niemasd/biowasm/tree/main/tools/agc

But I'm struggling to actually get it to compile locally. I tried writing a `compile.sh` as follows (note that we only need the `agc` Makefile target):

```bash
emmake make agc \
    CXX=em++ \
    EXE=../build/agc.js \
    CFLAGS="-fPIC -m64 -mavx -msimd128 -std=c++17 $EM_FLAGS" \
    LIBS="-lm -lpthread"
```

Would you be able to help me with adding `agc` to biowasm?

**Comment by robertaboukhalil** [comment]
Hi Niema! I'm getting a bunch of errors relating to SIMD.

If I fiddle with the SIMD imports a bit, I get further:

```diff
diff --git a/src/core/hs.h b/src/core/hs.h
index 59fc81e..0b78dd4 100644
--- a/src/core/hs.h
+++ b/src/core/hs.h
@@ -11,9 +11,8 @@
 // Date   : 2022-12-22
 // *******************************************************************************************
 
-#include <mmintrin.h>
+#include <immintrin.h>
 #include <cstdint>
-#include <xmmintrin.h>
 #include <cstddef>
 
 #include <algorithm>
diff --git a/src/core/utils.h b/src/core/utils.h
index 454406d..db18264 100644
--- a/src/core/utils.h
+++ b/src/core/utils.h
@@ -13,7 +13,6 @@
 
 #include "../core/defs.h"
 #include <mutex>
-#include <nmmintrin.h>
 #include <string>
 #include <random>
 #include <vector>
```

But that leaves an error: `must specify -mwasm64 to process wasm64 object files`. But doing so wouldn't make it possible to run it in the browser since only wasm32 is currently supported.

I think that's related to the `-m64` flag (64-bit), but if I remove that flag, I get a lot of warnings about shifting numbers by too many positions:

```
src/app/../core/utils.h:276:10: warning: shift count >= width of type [-Wshift-count-overflow]
                h ^= h >> 33;
                       ^  ~~
```

so the code does rely on 64-bit support.

So unless we modify the code so it works on 32-bit, I don't think we can compile this to WebAssembly.

**Comment by niemasd** [comment]
Thanks for looking into this! This is super helpful info; probably not worth looking into for now, then. Thanks!
